### PR TITLE
Fixing the selenium error on the travis tests

### PR DESCRIPTION
**Pull request by felipemontoya**
Making the tests run on travis

### CODE REVIEW

**Comment by felipemontoya** [comment]
The fixes where taken from [upstream](https://github.com/edx/ecommerce/commit/d8e2a81837ec07630d57264e284ceb7d39b97037)

**Comment by felipemontoya** [comment]
@jfavellar90

**Comment by jfavellar90** [comment]
:+1: (We trust on you)

**Comment by felipemontoya** [comment]
Nada de eso. Tiene que revisar ...

**Comment by jfavellar90** [comment]
Already did that, the thing is I can't guarantee it's working, only you

**Pull request merged**
